#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Uncomment to debug script
# set -o xtrace

# Current script dir
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_OS="$(uname -s)"

source ${DOTFILES_DIR}/lib/colors.bash

# Add Symlinks
source ${DOTFILES_DIR}/install-symlinks.bash

# Idempotent Install
for f in ${DOTFILES_DIR}/install-scripts/*; do [[ -f "${f}" ]] && source ${f}; done
if [ "${DOTFILES_OS}" == "Darwin" ]; then
  for f in $DOTFILES_DIR/install-scripts/osx/*; do [[ -f "$f" ]] && source $f; done
elif [ "${DOTFILES_OS}" == "Linux" ]; then
  for f in ${DOTFILES_DIR}/install-scripts/linux/*; do [[ -f "${f}" ]] && source ${f}; done
fi
unset f

# Local
[[ -f "${HOME}/.local/install" ]] && source ${HOME}/.local/install

unset DOTFILES_DIR
unset DOTFILES_OS

echo -e "${__COLORS_GREEN}All Done!${__COLORS_CLEAR}"
