#!/usr/bin/env bash

# Current script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Dependencies
command -v brew >/dev/null 2>&1 || { echo >&2 "Homebrew not found. Please install it from http://brew.sh/"; exit 1; }

set -x

# Idempotent Install
for f in $DIR/install-scripts/*; do [[ -f "$f" ]] && source $f; done
unset f

# Local
[[ -f "$HOME/.local/install" ]] && source $HOME/.local/install;

# Add Symlinks
ln -svi $DIR/.hushlogin $HOME/.hushlogin
ln -svi $DIR/.curlrc $HOME/.curlrc
ln -svi $DIR/.inputrc $HOME/.inputrc
ln -svi $DIR/.bashrc $HOME/.bashrc
ln -svi $DIR/.bash_profile $HOME/.bash_profile
ln -svi $DIR/.bash_completion $HOME/.bash_completion
