#!/usr/bin/env bash

brew install \
		git \
		node \
		go \
		composer \
		bash-completion \
		hub \
		awscli \
		jq \
		oniguruma \
		keybase

npm -g install \
		http-server \
		kkpoon-pushbullet-cli
