#!/usr/bin/env bash

aws_tokens() {
  local -r now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  local -r _aws_profiles=($@)
  local token_expiration=""
  local out=""

  for aws_profile in "${_aws_profiles[@]}"; do
    token_expiration="$(aws configure get profile.${aws_profile}.x_security_token_expires)"
    if [[ "${token_expiration}" && $(datediff "${now}" "${token_expiration}" -f '%S') -gt 0 ]]; then
      out="${out} [${aws_profile} $(datediff "${now}" "${token_expiration}" -f '%Mm')]"
    fi
  done

  echo ${out}
}

main() {
  if ! command -v aws > /dev/null; then
    return
  fi

  if ! command -v datediff > /dev/null; then
    return
  fi

  local -r aws_profiles="$(aws configure list-profiles)"
  local -r aws_tokens="$(aws_tokens ${aws_profiles})"

  echo ${aws_tokens} > /tmp/ps1_aws_tokens
}

main "$@"
